# Generated by Django 5.1.6 on 2025-04-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_profile_type_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aud_likes', to='music.audio'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vid_likes', to='music.video'),
        ),
    ]
