# Generated by Django 5.1.6 on 2025-04-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_like_audio_alter_like_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aud_likes', to='music.audio'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vid_likes', to='music.video'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Creator', 'Creator'), ('Audience', 'Audience')], default='Audience', max_length=20),
        ),
    ]
