# Generated by Django 5.1.6 on 2025-05-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_platform_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb',
            field=models.CharField(default='#', max_length=20000),
        ),
        migrations.AddField(
            model_name='profile',
            name='ig',
            field=models.CharField(default='#', max_length=20000),
        ),
        migrations.AddField(
            model_name='profile',
            name='tk',
            field=models.CharField(default='#', max_length=20000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Audience', 'Audience'), ('Creator', 'Creator')], default='Audience', max_length=20),
        ),
        migrations.CreateModel(
            name='Ft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=6000)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aud_fts', to='music.audio')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vid_fts', to='music.video')),
            ],
        ),
    ]
